[goggles]
enhancedInfo = true
hideStaticKineticInfo = false
betterStoreInfo = true
enableKineticEffect = true
preciseNumber = true
disableScreenGoggles = true
canRenderOnValueBox = false
[gameMode]
enableGoggles = true
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[overlay]
renderExtraItems = true
overlayOffsetX = 0
overlayOffsetY = 0
tooltipFlagType = "Default"
tooltipTheme = "Default"
useCustomColor = false
backgroundColor = 0
borderTopColor = 0
borderBottomColor = 0
[outliner]
renderAnalogBox = true
betterLine = true
delayRenderDuration = 60
outColor = 14532966
inColor = 8375776
rainbowDebug = false
[chainConveyor]
alwaysAllowRiding = false
preventFalling = false
enhancedConnection = true
cardBoardedYourself = false
[wrench]
fixRotationMenu = true
betterEncasedCogwheel = true
betterEncasedPipe = true
betterChassis = true
alwaysShowScrollValue = true
alwaysAllowRotating = false
leftClickFastDismantle = false
removeCooldown = true
enchancedRotationMenu = false
[misc]
preventSelectionDiscard = true
translateCatnip = true
infEditBoxLength = false
removeCardboardOverlay = true
removeNetheriteFirstPerson = false
allowDivingBoot = true
fixSchematicName = true
forcedBackend = false
nbtFix = false
showScrapContent = true
